version: '3.4'

services:
  postgres:
    image: postgres
  microservice1.api:
    container_name: microservice1-container
    image: microservice1-image
    build:
      context: .
      dockerfile: "MicroService1.API/Dockerfile"
  
  microservice2.api:
    container_name: microservice2-container
    image: microservice2-image
    build:
      context: .
      dockerfile: "MicroService2.API/Dockerfile"

volumes:
  postgres_volume: